import type { DesignPlan } from '../../shared/contracts.js';

export interface FigmaOperationPlan {
  version: 2;
  operationKey: string;
  target: {
    fileKey: string | null;
    requiresExistingFile: true;
  };
  capabilitiesRequired: string[];
  discovery: string[];
  operations: Array<Record<string, unknown>>;
  validation: string[];
}

export function createFigmaOperationPlan(plan: DesignPlan, runId: string, fileKey: string | null): FigmaOperationPlan {
  return {
    version: 2,
    operationKey: `figma:${runId}:v1`,
    target: { fileKey, requiresExistingFile: true },
    capabilitiesRequired: ['use_figma', 'get_metadata', 'get_screenshot'],
    discovery: [
      'Inspect target pages and existing screens.',
      'Resolve matching components through Code Connect, existing instances, then library search.',
      'Resolve variables and styles before creating nodes.',
    ],
    operations: [
      {
        op: 'create-wrapper',
        name: `XDB/${runId}/desktop`,
        layout: 'VERTICAL',
        width: 1440,
      },
      ...plan.sections.map((section) => ({
        op: 'compose-section',
        sectionId: section.id,
        sectionType: section.type,
        component: section.component,
        variant: section.variant,
        content: { headline: section.headline, body: section.body },
      })),
      {
        op: 'bind-design-tokens',
        tokens: plan.tokens,
      },
      {
        op: 'create-mobile-variant',
        name: `XDB/${runId}/mobile`,
        width: 390,
        sourceSections: plan.sections.map((section) => section.id),
      },
    ],
    validation: [
      'Return every created or mutated node ID.',
      'Assert the configured font family on free-standing text.',
      'Capture one desktop and one mobile composition screenshot.',
      'Fail on clipped text, overlap, unresolved images, or placeholder copy.',
    ],
  };
}

export function createFigmaExecutionScript(plan: DesignPlan, runId: string): string {
  const tokenMap = Object.fromEntries(plan.tokens.map((token) => [token.name, token.value]));
  const payload = JSON.stringify(
    {
      operationKey: `figma:${runId}:v1`,
      desktopName: `XDB/${runId}/desktop`,
      mobileName: `XDB/${runId}/mobile`,
      concept: plan.designDirection.primaryConcept,
      tokens: tokenMap,
      sections: plan.sections.map((section) => ({
        id: section.id,
        type: section.type,
        headline: section.headline,
        body: section.body,
      })),
    },
    null,
    2,
  );

  return `// Generated by XDB. Execute through Figma use_figma after inspecting the target design system.
const spec = ${payload};
const createdNodeIds = [];
const createdVariableIds = [];
const existingRoots = figma.currentPage.children.filter((child) => child.name === spec.desktopName || child.name === spec.mobileName);
if (existingRoots.length === 2) {
  return { success: true, replayed: true, operationKey: spec.operationKey, createdNodeIds: [], mutatedNodeIds: [], rootNodeIds: existingRoots.map((node) => node.id) };
}
if (existingRoots.length > 0) throw new Error('Partial XDB Figma operation detected. Inspect the existing root before retrying.');
let maxX = 0;
for (const child of figma.currentPage.children) maxX = Math.max(maxX, child.x + child.width);
const fonts = await figma.listAvailableFontsAsync();
const family = String(spec.tokens['font.family.body'] ?? 'Inter').split(',')[0].trim();
const regular = fonts.find(({ fontName }) => fontName.family === family && fontName.style === 'Regular')?.fontName;
const strong = fonts.find(({ fontName }) => fontName.family === family && ['Bold', 'Semi Bold', 'SemiBold'].includes(fontName.style))?.fontName;
if (!regular || !strong) throw new Error('The Design Plan font family is unavailable in the target Figma file.');
const requiredColorTokens = ['color.surface.canvas', 'color.accent.soft', 'color.text.primary', 'color.text.muted'];
if (requiredColorTokens.some((name) => !/^#[0-9A-Fa-f]{6}$/.test(String(spec.tokens[name] ?? '')))) {
  throw new Error('The Design Plan is missing a required Figma color token.');
}
await Promise.all([figma.loadFontAsync(regular), figma.loadFontAsync(strong)]);
const collections = await figma.variables.getLocalVariableCollectionsAsync();
const collectionName = 'XDB/' + spec.operationKey;
let collection = collections.find((candidate) => candidate.name === collectionName);
if (!collection) {
  collection = figma.variables.createVariableCollection(collectionName);
  collection.renameMode(collection.modes[0].modeId, 'Default');
}
const localVariables = await figma.variables.getLocalVariablesAsync();
const colors = {};
for (const [name, value] of Object.entries(spec.tokens)) {
  if (typeof value !== 'string' || !/^#[0-9A-Fa-f]{6}$/.test(value)) continue;
  let variable = localVariables.find((candidate) => candidate.variableCollectionId === collection.id && candidate.name === name);
  if (!variable) {
    variable = figma.variables.createVariable(name, collection, 'COLOR');
    variable.scopes = name.includes('text') ? ['TEXT_FILL'] : ['FRAME_FILL', 'SHAPE_FILL'];
    createdVariableIds.push(variable.id);
  }
  const rgb = value.slice(1).match(/.{2}/g).map((part) => parseInt(part, 16) / 255);
  variable.setValueForMode(collection.modes[0].modeId, { r: rgb[0], g: rgb[1], b: rgb[2], a: 1 });
  colors[name] = variable;
}
const bindFill = (node, variable) => {
  node.fills = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', variable)];
};
const createView = (name, width, x, mobile) => {
  const wrapper = figma.createAutoLayout('VERTICAL', { name });
  wrapper.resize(width, 100);
  wrapper.x = x;
  wrapper.y = 0;
  wrapper.itemSpacing = 0;
  bindFill(wrapper, colors['color.surface.canvas']);
  createdNodeIds.push(wrapper.id);
  for (const sectionSpec of spec.sections) {
    const section = figma.createAutoLayout('VERTICAL', { name: sectionSpec.id, itemSpacing: mobile ? 12 : 18 });
    section.resize(width, 100);
    section.paddingLeft = mobile ? 24 : 120;
    section.paddingRight = mobile ? 24 : 120;
    section.paddingTop = mobile ? 44 : 72;
    section.paddingBottom = mobile ? 44 : 72;
    wrapper.appendChild(section);
    section.layoutSizingHorizontal = 'FILL';
    if (sectionSpec.type === 'hero' || sectionSpec.type === 'cta') bindFill(section, colors['color.accent.soft']);
    const heading = figma.createText();
    heading.fontName = strong;
    heading.fontSize = sectionSpec.type === 'hero' ? (mobile ? 42 : 68) : (mobile ? 28 : 42);
    heading.resize(mobile ? width - 48 : Math.min(920, width - 240), 20);
    heading.textAutoResize = 'HEIGHT';
    heading.characters = sectionSpec.headline;
    bindFill(heading, colors['color.text.primary']);
    section.appendChild(heading);
    const body = figma.createText();
    body.fontName = regular;
    body.fontSize = mobile ? 16 : 18;
    body.lineHeight = { unit: 'PERCENT', value: 160 };
    body.resize(mobile ? width - 48 : Math.min(720, width - 240), 20);
    body.textAutoResize = 'HEIGHT';
    body.characters = sectionSpec.body;
    bindFill(body, colors['color.text.muted']);
    section.appendChild(body);
    createdNodeIds.push(section.id, heading.id, body.id);
  }
  return wrapper;
};
const desktop = createView(spec.desktopName, 1440, maxX + 200, false);
const mobile = createView(spec.mobileName, 390, desktop.x + desktop.width + 200, true);
return {
  success: true,
  replayed: false,
  operationKey: spec.operationKey,
  createdNodeIds,
  mutatedNodeIds: [],
  createdVariableIds,
  rootNodeIds: [desktop.id, mobile.id],
  sectionCount: spec.sections.length,
};
`;
}
