import type { DesignPlan } from '../../shared/contracts.js';

export interface FigmaOperationPlan {
  version: 1;
  target: {
    fileKey: string | null;
    requiresExistingFile: true;
  };
  capabilitiesRequired: string[];
  discovery: string[];
  operations: Array<Record<string, unknown>>;
  validation: string[];
}

export function createFigmaOperationPlan(plan: DesignPlan, fileKey: string | null): FigmaOperationPlan {
  return {
    version: 1,
    target: { fileKey, requiresExistingFile: true },
    capabilitiesRequired: ['use_figma', 'get_metadata', 'get_screenshot'],
    discovery: [
      'Inspect target pages and existing screens.',
      'Resolve matching components through Code Connect, existing instances, then library search.',
      'Resolve variables and styles before creating nodes.',
    ],
    operations: [
      {
        op: 'create-wrapper',
        name: `${plan.designDirection.primaryConcept} / Landing page`,
        layout: 'VERTICAL',
        width: 1440,
      },
      ...plan.sections.map((section) => ({
        op: 'compose-section',
        sectionId: section.id,
        sectionType: section.type,
        component: section.component,
        variant: section.variant,
        content: { headline: section.headline, body: section.body },
      })),
      {
        op: 'bind-design-tokens',
        tokens: plan.tokens,
      },
      {
        op: 'create-mobile-variant',
        width: 390,
        sourceSections: plan.sections.map((section) => section.id),
      },
    ],
    validation: [
      'Return every created or mutated node ID.',
      'Assert the configured font family on free-standing text.',
      'Capture one desktop and one mobile composition screenshot.',
      'Fail on clipped text, overlap, unresolved images, or placeholder copy.',
    ],
  };
}

export function createFigmaExecutionScript(plan: DesignPlan): string {
  const payload = JSON.stringify(
    {
      name: `${plan.designDirection.primaryConcept} / Landing page`,
      sections: plan.sections.map((section) => ({
        id: section.id,
        type: section.type,
        headline: section.headline,
        body: section.body,
      })),
    },
    null,
    2,
  );

  return `// Generated by XDB. Execute through Figma use_figma after inspecting the target design system.
const spec = ${payload};
const createdNodeIds = [];
let maxX = 0;
for (const child of figma.currentPage.children) maxX = Math.max(maxX, child.x + child.width);
const wrapper = figma.createAutoLayout('VERTICAL', { name: spec.name });
wrapper.resize(1440, 100);
wrapper.x = maxX + 200;
wrapper.y = 0;
wrapper.itemSpacing = 0;
wrapper.fills = [{ type: 'SOLID', color: { r: 0.961, g: 0.957, b: 0.937 } }];
createdNodeIds.push(wrapper.id);
const fonts = await figma.listAvailableFontsAsync();
const preferred = fonts.find(({ fontName }) => fontName.family === 'Inter' && fontName.style === 'Regular')?.fontName;
if (!preferred) throw new Error('Required font Inter Regular is unavailable. Resolve the product font before retrying.');
await figma.loadFontAsync(preferred);
for (const sectionSpec of spec.sections) {
  const section = figma.createAutoLayout('VERTICAL', { name: sectionSpec.id, itemSpacing: 16 });
  section.resize(1440, 100);
  section.paddingLeft = 120;
  section.paddingRight = 120;
  section.paddingTop = 72;
  section.paddingBottom = 72;
  wrapper.appendChild(section);
  section.layoutSizingHorizontal = 'FILL';
  const heading = figma.createText();
  heading.fontName = preferred;
  heading.characters = sectionSpec.headline;
  heading.fontSize = sectionSpec.type === 'hero' ? 64 : 40;
  heading.textAutoResize = 'HEIGHT';
  heading.resize(920, heading.height);
  section.appendChild(heading);
  const body = figma.createText();
  body.fontName = preferred;
  body.characters = sectionSpec.body;
  body.fontSize = 18;
  body.textAutoResize = 'HEIGHT';
  body.resize(720, body.height);
  section.appendChild(body);
  createdNodeIds.push(section.id, heading.id, body.id);
}
await wrapper.screenshot();
return { success: true, createdNodeIds, sectionCount: spec.sections.length, wrapperId: wrapper.id };
`;
}
